## Numpy For Data Science

### Creating Numpy Array

In [1]:
# importing
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [4]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [5]:
np.array([1,2,3], dtype=int)

array([1, 2, 3])

In [6]:
np.array([1,2,0], dtype=bool)

array([ True,  True, False])

In [7]:
# arange --> Creating range of numbers
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# can provide step too
np.arange(0, 11, 3)

array([0, 3, 6, 9])

In [9]:
# reshape
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
# np.ones --> Create Array of All ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# np.zeroes --> Create an array of all zeroes
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# np.random.random  --> Create an array of random number between 0 and 1
np.random.random((3,2))

array([[0.37901336, 0.21924053],
       [0.75286498, 0.67737796],
       [0.77661221, 0.95901743]])

In [13]:
# np.linspace --> Evenly spaced array of n value
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
# to create identiy matrix of size n*n
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Numpy Array Attributes

In [15]:
# lets create 3 arrays
a1 =np.arange(10)
a2 =np.arange(10).reshape(2, 5)
a3 =np.arange(8).reshape(2,2,2)


In [16]:
# ndim
print(a1.ndim, a2.ndim, a3.ndim)

1 2 3


In [17]:
# shape
print(a1.shape, a2.shape, a3.shape)

(10,) (2, 5) (2, 2, 2)


In [18]:
# size --> Total number of items
print(a1.size, a2.size, a3.size)

10 10 8


In [19]:
# itemsize --> Size of Each item (How many bytes)
print(a1.itemsize)

4


In [20]:
# 32/8 =4 Bytes
a1.dtype

dtype('int32')

In [21]:
# to change dtype
a1 =a1.astype("int8")

In [22]:
# now taking only 1 byte
a1.itemsize

1

In [23]:
# dtype to check datatype of items
a1.dtype

dtype('int8')

## Array Operations

In [24]:
arr =np.arange(12, 24).reshape(4,3)
arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [25]:
# Arithmetic Operations
arr + 2

array([[14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25]])

In [26]:
arr -2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [27]:
arr / 2

array([[ 6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. ],
       [10.5, 11. , 11.5]])

In [28]:
arr * 2

array([[24, 26, 28],
       [30, 32, 34],
       [36, 38, 40],
       [42, 44, 46]])

In [29]:
arr ** 2

array([[144, 169, 196],
       [225, 256, 289],
       [324, 361, 400],
       [441, 484, 529]])

In [30]:
arr % 2

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [31]:
# Relational Operations
arr > 20

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [32]:
arr >=20

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [33]:
arr < 20

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [463]:
arr <=20

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [34]:
arr !=20

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [35]:
arr == 20

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [36]:
# Vector operation
arr2 =np.full(arr.shape, 5)
arr2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [37]:
arr + arr2

array([[17, 18, 19],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

## Array Functions

In [38]:
arr =np.random.random((10, 10))
arr

array([[6.46259735e-01, 4.58480313e-01, 1.97081515e-01, 3.44589734e-01,
        3.93862318e-04, 3.31399582e-02, 1.40855386e-01, 5.95689105e-01,
        8.92044538e-01, 5.28194709e-01],
       [3.88573582e-01, 4.84217783e-01, 1.93143589e-01, 5.22767391e-01,
        3.95417880e-01, 5.15070762e-01, 4.49008440e-01, 3.95125574e-01,
        7.66043459e-03, 7.38340925e-01],
       [7.80080501e-01, 7.20535622e-01, 7.16038342e-01, 8.98199037e-01,
        7.61188442e-01, 2.57885056e-01, 4.30775426e-01, 6.69129408e-01,
        8.95250285e-01, 6.31961903e-01],
       [5.99750487e-01, 2.98714998e-01, 4.79644236e-01, 9.94858853e-01,
        1.29550499e-01, 8.77345304e-01, 7.27844431e-01, 2.48143669e-02,
        4.75054142e-01, 2.14011990e-02],
       [8.95578627e-01, 9.64943729e-01, 4.43707554e-01, 3.68632253e-01,
        2.19733865e-01, 8.89175749e-01, 3.21597616e-01, 4.43308537e-01,
        8.50857620e-01, 3.47596323e-01],
       [3.36581066e-02, 1.42380628e-01, 9.05632995e-01, 6.40055729e-01,
   

In [39]:
np.max(arr)

0.9948588528989292

In [40]:
np.min(arr)

0.00039386231762250645

In [41]:
np.sum(arr)

49.56494680296559

In [42]:
np.prod(arr)

3.216163900409091e-47

In [43]:
# Hoe to find max from each row
# 0--> Col
# 1 --> Row
# same for all funct
np.max(arr, axis =1)

array([0.89204454, 0.73834092, 0.89819904, 0.99485885, 0.96494373,
       0.905633  , 0.91411724, 0.98582356, 0.82203207, 0.99197595])

In [44]:
np.sum(arr, axis =1)

array([3.83672885, 4.08932636, 6.76104402, 4.62897852, 5.74513187,
       3.98330938, 4.1340353 , 6.14149282, 4.50463134, 5.74026833])

In [45]:
# mean/median, std deviation, var
np.mean(arr)

0.4956494680296559

In [46]:
np.median(arr)

0.4863739024912902

In [47]:
np.std(arr)

0.28290527235417867

In [48]:
np.var(arr)

0.080035393125792

In [49]:
# dot product
arr1 =np.random.random((10, 1))


In [50]:
np.dot(arr, arr1)

array([[1.60037457],
       [2.07665912],
       [3.26310716],
       [2.11312319],
       [2.47273598],
       [2.17709372],
       [1.98195993],
       [2.78970882],
       [2.53046552],
       [2.73357487]])

In [51]:
# floor
np.floor(np.random.random((10, 10))*10)

array([[2., 1., 1., 2., 7., 0., 2., 3., 0., 9.],
       [2., 5., 2., 7., 6., 5., 3., 2., 9., 9.],
       [1., 3., 5., 7., 2., 8., 4., 1., 2., 3.],
       [9., 6., 2., 3., 8., 1., 4., 9., 5., 7.],
       [0., 5., 0., 1., 5., 0., 5., 9., 5., 8.],
       [0., 3., 0., 0., 2., 2., 9., 0., 1., 3.],
       [7., 2., 2., 5., 3., 3., 5., 8., 8., 1.],
       [5., 0., 6., 0., 7., 7., 8., 7., 5., 9.],
       [6., 8., 8., 1., 5., 8., 8., 1., 3., 1.],
       [5., 7., 0., 0., 8., 4., 7., 2., 1., 5.]])

In [52]:
np.ceil(np.random.random((10, 10))*10)

array([[ 3.,  9.,  6., 10.,  3.,  9.,  9.,  9., 10.,  9.],
       [ 1., 10.,  9.,  2.,  7.,  2.,  6.,  3.,  7.,  3.],
       [ 1.,  9.,  8.,  4.,  1.,  6.,  3.,  3.,  2.,  4.],
       [ 9.,  7.,  1.,  7.,  7.,  6., 10.,  1.,  4.,  1.],
       [ 9.,  6.,  1.,  3.,  5.,  2.,  4.,  8.,  5.,  7.],
       [10.,  2.,  5.,  2.,  8.,  1.,  3., 10.,  1.,  4.],
       [ 8.,  1., 10.,  1., 10.,  6.,  4.,  4.,  8.,  4.],
       [10.,  4.,  9.,  2.,  8.,  9.,  2.,  1.,  9.,  6.],
       [ 1.,  5.,  2.,  1., 10., 10.,  4.,  9.,  9.,  8.],
       [ 7.,  9.,  3., 10.,  1.,  5., 10.,  3.,  1.,  1.]])

In [53]:
np.round((np.random.random((10, 10)))* 10)

array([[ 0.,  9.,  2.,  1.,  9.,  1.,  1.,  5.,  5.,  0.],
       [ 7.,  7.,  5.,  5.,  1.,  4.,  4.,  3.,  3.,  1.],
       [ 8.,  9.,  6.,  6.,  6.,  4.,  6.,  5.,  7.,  2.],
       [ 0.,  2.,  6.,  1.,  4.,  7., 10.,  3.,  5.,  1.],
       [10.,  4.,  4.,  9.,  8.,  7.,  5.,  9.,  9.,  5.],
       [ 5.,  2.,  3.,  8.,  7.,  5.,  0.,  8.,  3.,  6.],
       [ 1.,  4., 10.,  4.,  3.,  8.,  3.,  3.,  3.,  6.],
       [10.,  4.,  6.,  5.,  5.,  6.,  6.,  8.,  7.,  8.],
       [ 1.,  0.,  1., 10.,  2.,  8., 10.,  6.,  9.,  8.],
       [ 9.,  7.,  5.,  4.,  3.,  2.,  5.,  8.,  9.,  4.]])

## Indexing Slicing

In [54]:
a1 =np.arange(10)
a2 =np.arange(10).reshape(2, 5)
a3 =np.arange(8).reshape(2,2,2)

### Indexing

In [55]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# positive indexing
# starts from left 
# want to get value 3
a1[3]

3

In [57]:
a1[-1]

9

In [58]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
# want to fetch value 8
a2[1, 3]

8

In [60]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
# want to fetch 6
a3[1,1, 0]

6

### Slicing

In [62]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# want o get 2,3, 4
a1[2:5]

array([2, 3, 4])

In [64]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
a2[:,4]

array([4, 9])

In [66]:
# want to fetch first row
a2[0,:]

array([0, 1, 2, 3, 4])

In [67]:
a2[0,2:4]

array([2, 3])

In [68]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
a3 = np.arange(27).reshape(3,3,3)

In [71]:
a3 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [72]:
# Getting second matrix
a3[1, ]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [73]:
# getting other than 1
a3[0::2,]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
a3[0, 1,]

array([3, 4, 5])

In [75]:
a3[1, :, 1]

array([10, 13, 16])

In [76]:
# fetch 22 , 23, 25, 26
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [77]:
a3[0::2,0, 0::2]

array([[ 0,  2],
       [18, 20]])

## Iteration On NumPy Array

In [78]:
# Iteration on 1d
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [79]:
# on 2d
for i in a2:
    print(i, end =" ")

[0 1 2 3 4] [5 6 7 8 9] 

In [80]:
# on 3d
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [81]:
for i in a3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [82]:
# more ezy way 
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Transpose

In [83]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
np.transpose(a2)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## Ravel
- Convert ndim array into 1d

In [85]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [86]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking
- Horizontal
- Vertical

In [87]:
a4 =np.arange(0, 10).reshape(2, 5)
a5 =np.arange(11, 23).reshape(2, 6)
a4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15, 16],
       [ 5,  6,  7,  8,  9, 17, 18, 19, 20, 21, 22]])

In [89]:
a4 =np.arange(0, 10).reshape(5, 2)
a5 =np.arange(11, 23).reshape(6, 2)

In [90]:
np.vstack((a4, a5))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22]])

## Splitting

In [91]:
a4 =np.arange(0, 10).reshape(2, 5)
a5 =np.arange(11, 21).reshape(2, 5)
arr =np.hstack((a4, a5))
arr

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [92]:
np.hsplit(arr, 2)


[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [93]:
np.vsplit(arr, 2)

[array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15]]),
 array([[ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])]

In [94]:
a4 =np.arange(0, 10).reshape(5, 2)
a5 =np.arange(11, 21).reshape(5, 2)
arr =np.vstack((a4, a5))
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [95]:
np.vsplit(arr, 2)


[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])]

## Advance Numpy

### Fancy Indexing

In [96]:
arr =np.arange(0, 12).reshape(4, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [97]:
# want 0,1,4 row
arr[[0,1,3],:]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11]])

## Boolean Indexing

In [98]:
arr =np.random.randint(1, 100, 24).reshape(6, 4)

In [99]:
# Find all number greater than 20
arr[arr > 20]

array([37, 46, 53, 94, 71, 47, 30, 45, 79, 38, 85, 43, 26, 60, 65, 78, 93,
       98, 65, 43])

In [100]:
# Find all number greater than 50 and even
arr [(arr>50) & (arr%2==0)]

array([94, 60, 78, 98])

## Broadcasting

In [101]:
# same shape
arr =np.arange(6).reshape(2, 3)
arr2 =np.arange(6, 12).reshape(2, 3)
print(arr)
print(arr2)
print(arr + arr2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [102]:
# differ shape
arr =np.arange(6).reshape(2, 3)
arr2 =np.arange(6, 9).reshape(1, 3)
print(arr)
print(arr2)
print(arr + arr2)

[[0 1 2]
 [3 4 5]]
[[6 7 8]]
[[ 6  8 10]
 [ 9 11 13]]


## Rules
- Same Number of Dimension (add 1 to head)
- Exp: (3,3) and second is (3,) make second one (1,3)
- Make each dimension of same size (stretch 1 to size of another array)

In [103]:
# exp 1
# 1. strect (3, ) to (1, 3)
# 2. Make (1,3) to (3,3) and add

a =np.arange(0, 9).reshape(3,3)
b =np.arange(3)
print(a,b)
print(a+b)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [104]:
# exp 2 --> Will throw error
a =np.arange(0, 12).reshape(3,4)
b =np.arange(3)
print(a, b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a =np.arange(3).reshape(1,3)
b =np.arange(3).reshape(3,1)
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a =np.arange(3).reshape(1, 3)
b =np.arange(4).reshape(4, 1)
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
a =np.array([4])
b =np.arange(4).reshape(2,2)
print(a+b)

[[4 5]
 [6 7]]


## Mathematical Operations

In [ ]:
# sigmoid
a =np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

a = 1/(1+ np.exp(a))
a


array([5.00000000e-01, 2.68941421e-01, 1.19202922e-01, 4.74258732e-02,
       1.79862100e-02, 6.69285092e-03, 2.47262316e-03, 9.11051194e-04,
       3.35350130e-04, 1.23394576e-04])

In [ ]:
# mean sqaured error
actual =np.array([0, 0, 0])
predicted=np.array([1,2,3])

In [ ]:
def mse(actual, predicted):
    return np.sum((actual-predicted)**2)/actual.shape[0]
mse(actual, predicted)

4.666666666666667

In [ ]:
# missing values
a =np.array([1,2,3,np.nan])
a

array([ 1.,  2.,  3., nan])

In [ ]:
np.isnan(a)

array([False, False, False,  True])

In [ ]:
a[np.isnan(a)]

array([nan])

## Numpy Tricks

### Sort Numpy Array

In [ ]:
a =np.random.randint(1, 100, 12)
a

array([15, 38, 39, 26, 25, 72, 88, 38, 11, 18, 93, 57])

In [ ]:
b =np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[30, 56, 21, 21],
       [53, 17, 36, 93],
       [42, 19, 55, 76],
       [93, 67, 22, 54],
       [21, 14, 48,  9],
       [78, 53, 84, 28]])

In [ ]:
# Sorting 1d array
np.sort(a)

array([11, 15, 18, 25, 26, 38, 38, 39, 57, 72, 88, 93])

In [ ]:
# How to reverse sort
np.sort(a)[::-1]

array([93, 88, 72, 57, 39, 38, 38, 26, 25, 18, 15, 11])

In [ ]:
# Sort 2d array
# 1 for row 
# 0 for col
np.sort(b)

array([[ 1, 46, 82, 88],
       [ 2,  8, 11, 75],
       [11, 53, 61, 82],
       [28, 43, 48, 60],
       [15, 30, 40, 56],
       [13, 25, 27, 75]])

In [ ]:
np.sort(b, axis =0)

array([[ 8, 11,  1,  2],
       [27, 11, 13, 15],
       [30, 28, 40, 25],
       [46, 56, 43, 53],
       [48, 75, 75, 60],
       [61, 88, 82, 82]])

### Append

In [ ]:
np.append(a, 100)

array([ 15,  38,  39,  26,  25,  72,  88,  38,  11,  18,  93,  57, 100])

### Unique 

In [ ]:
np.unique(np.array([1,2,3,4,5,5,5,5]))

array([1, 2, 3, 4, 5])

### Where
- Return indices of elements in Array where specific condition is specified

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.where(a>10)

(array([2], dtype=int64), array([3], dtype=int64))

In [ ]:
# replace all value with some value if cond is trye
np.where(a>10, 100, 0)

array([[  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0, 100]])

### ArgMax and ArgMin

In [ ]:
a =np.random.randint(1, 100, 12)
a

array([89, 47, 80, 33,  4, 67, 34, 57, 92, 63, 38, 67])

In [ ]:
b =np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[48, 92, 30, 58],
       [58, 69, 79, 86],
       [47, 39, 27, 15],
       [22, 36, 97, 11],
       [43,  5, 43, 46],
       [96, 46, 33, 95]])

In [ ]:
# Find indices of max value in arr a
np.argmax(a)

8

In [ ]:
np.argmin(a)

4

In [ ]:
np.argmax(b, axis =0)

array([5, 0, 3, 5], dtype=int64)

### Cumsum and Cumprod

In [ ]:
a

array([89, 47, 80, 33,  4, 67, 34, 57, 92, 63, 38, 67])

In [ ]:
np.cumsum(a)

array([ 89, 136, 216, 249, 253, 320, 354, 411, 503, 566, 604, 671])

In [ ]:
np.cumsum(b, axis =0)

array([[ 48,  92,  30,  58],
       [106, 161, 109, 144],
       [153, 200, 136, 159],
       [175, 236, 233, 170],
       [218, 241, 276, 216],
       [314, 287, 309, 311]])

### Histogram
- Returns distribution of Data

In [ ]:
a

array([89, 47, 80, 33,  4, 67, 34, 57, 92, 63, 38, 67])

In [ ]:
np.histogram(a, bins =[0,50, 100])

(array([5, 7], dtype=int64), array([  0,  50, 100]))

### CorrCoef

In [ ]:
salary =np.array([10, 20, 30, 40])
exp =np.array([1,2,3,4])

In [ ]:
np.corrcoef(salary, exp)

array([[1., 1.],
       [1., 1.]])

### Isin

In [ ]:
a

array([89, 47, 80, 33,  4, 67, 34, 57, 92, 63, 38, 67])

In [ ]:
z =np.arange(20)
np.isin(a, z)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False])

### Put

In [ ]:
a

array([89, 47, 80, 33,  4, 67, 34, 57, 92, 63, 38, 67])

In [ ]:
np.put(a, [0, 1], [100, 110])


In [ ]:
a

array([100, 110,  80,  33,   4,  67,  34,  57,  92,  63,  38,  67])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])