# Numpy

In [1]:
# Why Numpy?
# Faster to read
# Fixed type
# Contiguous Memory (List are not) So we can,
#SIMD (single instruction multiple data) vector processing(can perform multiple operation at single time)


# Basics

In [2]:
import numpy as np

In [3]:
#Its a vector --> One col
a =np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
b =np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Get Dimmension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Getting Shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# By default int in numpy takes 4 bytes you can change usig dtype attribute
a.dtype

dtype('int32')

In [10]:
# How many bytes single element of arr is taking?? so int32 32bits/8=4 bytes
a.itemsize

4

In [11]:
b.itemsize

4

In [12]:
# No. of elements in a
a.size

3

In [13]:
b.size

6

In [14]:
# Total number of bytes arr is taking

a.size * a.itemsize

12

In [15]:
# Can also use this
a.nbytes

12

# Accessing Specific rows, cols, elements etc

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# Accessing a specific val
b[1, 1]

5

In [18]:
# Accessing a specific row
b[1, :]

array([4, 5, 6])

In [19]:
# Accessing a specific col
b[:, 1]

array([2, 5])

In [20]:
b =np.array([[1,2,3,4,5], [5,6,7,8,9]])
b

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [21]:
# Fancy way startindex:end:step
b[0, 1:4:2]

array([2, 4])

In [22]:
c =np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
c[0:3:2, 1:4:2]

array([[ 2,  4],
       [12, 14]])

# Changing Elements

In [24]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
# Changing specific val
c[1, 2] =10
1

1

In [26]:
# Changing specific row
c[0] =[11,12,13,14,15]
c

array([[11, 12, 13, 14, 15],
       [ 6,  7, 10,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
# Changing specific col
c[:, 1] =[3,4,5]
c

array([[11,  3, 13, 14, 15],
       [ 6,  4, 10,  9, 10],
       [11,  5, 13, 14, 15]])

# Initializing Different types of arrays

In [28]:
# All 0s
print(np.zeros((3,), dtype="int32"))
print(np.zeros((3,4)))
print(np.zeros((3,3,3)))

[0 0 0]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [29]:
# All 1s
print(np.ones((3,), dtype="int32"))
print(np.ones((3,4)))
print(np.ones((3,3,3)))

[1 1 1]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [30]:
# Any other number
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [31]:
b

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [32]:
# Any other number (full like)
np.full_like(b, 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [33]:
# Random (float)
np.random.random_sample(b.shape)

array([[0.75245548, 0.66447836, 0.06403557, 0.59212399, 0.44261807],
       [0.09829166, 0.15024192, 0.3498616 , 0.90747022, 0.72781143]])

In [34]:
# Random (int)
# This will create array of size 4*4 fro, rand int values from 0 to 8
np.random.randint(0, 8, size=(4,4))

array([[1, 2, 6, 6],
       [0, 7, 2, 0],
       [4, 6, 1, 7],
       [5, 5, 3, 3]])

In [35]:
# Identity Matrix (always sqaure)
np.identity(5, dtype="int16")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [36]:
arr =np.array([[1,2,3]])
# axis 1 will place them in one row
np.repeat(arr, 3, axis=0)


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Be careful while copying arrays!!

In [37]:
a =np.array([1,2,3])
# This will point to sme location so changing val of b will also change val of a and vice versa
b =a
b[0] =100
print(a, b)

[100   2   3] [100   2   3]


In [38]:
a =np.array([1,2,3])
b =a.copy()
b[0] =100
print(a, b)

[1 2 3] [100   2   3]


# Mathematics

In [39]:
a =np.array([1,2,3])
a + 2
a

array([1, 2, 3])

In [40]:
a -2
a

array([1, 2, 3])

In [41]:
a * 2

array([2, 4, 6])

In [42]:
a / 2

array([0.5, 1. , 1.5])

In [43]:
a **2


array([1, 4, 9])

In [44]:
#This will change original array too
a -=2
a

array([-1,  0,  1])

In [45]:
a =np.array([1,2,3])
b =np.array([2,3,4])
a + b


array([3, 5, 7])

# Very Basic Stats

In [46]:
a =np.random.randint(0, 9, size =(3,3))
a

array([[8, 4, 3],
       [3, 4, 1],
       [3, 4, 7]])

In [47]:
# axis 0 means min col wise same for max 
np.min(a, axis =0)

array([3, 4, 1])

In [48]:
np.sum(a, axis =1)

array([15,  8, 14])

# Reorganzing Arrays

In [49]:
before =np.array([1,2,3,4,5,6,7,8,9,10])
before.reshape((2, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
a =np.array([1,2,3,4])
b =np.array([5,6,7,8])
horizonstal_stack =np.hstack([a, b])
verticla_Stack =np.vstack([a, b])
print(horizonstal_stack,"\n", verticla_Stack)

[1 2 3 4 5 6 7 8] 
 [[1 2 3 4]
 [5 6 7 8]]


# Miscellaneous

### Load Data From File

In [53]:
txtdata =np.genfromtxt("sample.csv", delimiter=",")
txtdata =txtdata.astype("int8")
txtdata

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

### Boolean Masking and Advance Indexing

In [54]:
txtdata > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
txtdata[ txtdata > 2]

array([3, 4, 5, 6, 7, 8], dtype=int8)

In [56]:
txtdata[(txtdata >2) | (txtdata==8)]

array([3, 4, 5, 6, 7, 8], dtype=int8)

In [57]:
# Indexing using list
hhe =np.array([1,2,3])
hhe[[0,1]]

array([1, 2])